version: "2"

run:
  build-tags:
    - unit
    - integration
    - smoke
    - regression

linters:
  enable:
    - govet
    - misspell
    - unused

formatters:
  enable:
    - goimports
    - gofmt

issues:
  max-issues-per-linter: 50
  max-same-issues: 10
