.PHONY: test-unit test-integration test-all test-smoke test-regression

test-unit:
	go test -v -tags=unit ./api/...

test-integration:
	go test -v -tags=integration -timeout=120s ./api/...

test-all:
	go test -v -tags=unit ./api/... && go test -v -tags=integration -timeout=120s ./api/... && go test -v -tags=smoke -timeout=60s ./api/...

test-smoke:
	go test -v -tags=smoke -timeout=60s ./api/...

test-regression:
	go test -v -tags=regression -timeout=120s ./api/...
